### ISSUE TITLE
Settings service doesnot work with ocis

### ISSUE THREAD

**Issue by dpakach** [owncloud/ocis-settings#37]
When I set up the ocis-settings with ocis, I get the following error, and changing a setting does not work.
```
2020-07-22 12:04:53.511264 I | http: panic serving 127.0.0.1:41730: interface conversion: interface {} is nil, not string
goroutine 61 [running]:
net/http.(*conn).serve.func1(0xc000370000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x19ba240, 0xc000348de0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/owncloud/ocis-settings/pkg/service/v0.getFailsafeIdentifier(0x1dc8680, 0xc0001e1dd0, 0xc00038e000, 0xc000322008)
	/home/dipakacharya/go/src/github.com/owncloud/ocis-settings/pkg/service/v0/service.go:118 +0x17d
github.com/owncloud/ocis-settings/pkg/service/v0.Service.SaveSettingsValue(0xc000228000, 0x1dd1340, 0xc000538000, 0x1dc8680, 0xc0001e1dd0, 0xc0001e1e00, 0xc0001e1e60, 0x0, 0xc00056a160)
	/home/dipakacharya/go/src/github.com/owncloud/ocis-settings/pkg/service/v0/service.go:72 +0x4b
github.com/owncloud/ocis-settings/pkg/proto/v0.(*webValueServiceHandler).SaveSettingsValue(0xc00000ff00, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/home/dipakacharya/go/src/github.com/owncloud/ocis-settings/pkg/proto/v0/settings.pb.web.go:128 +0x179
net/http.HandlerFunc.ServeHTTP(0xc00007a480, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0001a5d40, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00042dfb0, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0001a5d40, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:70 +0x513
github.com/go-chi/chi.(*Mux).Mount.func1(0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:298 +0x121
net/http.HandlerFunc.ServeHTTP(0xc00000ffe0, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0001a5aa0, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00007abb0, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.Static.func1.1(0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/static.go:25 +0x1cf
net/http.HandlerFunc.ServeHTTP(0xc000455200, 0x7f89782eda50, 0xc0002656c0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.Logger.func1.1(0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/logger.go:17 +0x1d9
net/http.HandlerFunc.ServeHTTP(0xc000548020, 0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.Version.func1.1(0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/version.go:18 +0x213
net/http.HandlerFunc.ServeHTTP(0xc000455240, 0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.ExtractAccountUUID.func1.1(0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/account.go:39 +0x4b2
net/http.HandlerFunc.ServeHTTP(0xc00053c8d0, 0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.Secure.func1(0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/header.go:47 +0x3d0
net/http.HandlerFunc.ServeHTTP(0xc0005481c0, 0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.Cors.func1(0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/header.go:23 +0x5e
net/http.HandlerFunc.ServeHTTP(0xc0005481e0, 0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.Cache.func1(0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/header.go:15 +0x3d5
net/http.HandlerFunc.ServeHTTP(0xc000548200, 0x1dc2d40, 0xc0003920e0, 0xc000378200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/ascarter/requestid.RequestIDHandler.func1(0x1dc2d40, 0xc0003920e0, 0xc000378100)
	/home/dipakacharya/go/pkg/mod/github.com/ascarter/requestid@v0.0.0-20170313220838-5b76ab3d4aee/requestid.go:36 +0x1f0
net/http.HandlerFunc.ServeHTTP(0xc000548260, 0x1dc2d40, 0xc0003920e0, 0xc000378100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/owncloud/ocis-pkg/v2/middleware.RealIP.func1(0x1dc2d40, 0xc0003920e0, 0xc000378100)
	/home/dipakacharya/go/pkg/mod/github.com/owncloud/ocis-pkg/v2@v2.2.2-0.20200527082518-5641fa4a4c8c/middleware/realip.go:16 +0x99
net/http.HandlerFunc.ServeHTTP(0xc000548280, 0x1dc2d40, 0xc0003920e0, 0xc000378100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0001a5aa0, 0x1dc2d40, 0xc0003920e0, 0xc000378000)
	/home/dipakacharya/go/pkg/mod/github.com/go-chi/chi@v4.1.0+incompatible/mux.go:86 +0x2b2
net/http.(*ServeMux).ServeHTTP(0xc0000a5d00, 0x1dc2d40, 0xc0003920e0, 0xc000378000)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc0002e2460, 0x1dc2d40, 0xc0003920e0, 0xc000378000)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000370000, 0x1dc85c0, 0xc000265500)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

**Comment by individual-it** [comment]
@kulmann could you unblock here?

**Comment by refs** [comment]
👀
